In [20]:
import pandas as pd
import numpy as np
data={"department":["IT","IT","HR","finance","HR","IT"],
       "Employee":["A","B","C","D","E","F"],
        "Salary":[50000,60000,65000,45000,70000,70000],
         "Experience":[2,4,3,1,4,5]}
df=pd.DataFrame(data)
df.groupby('department')
print(df)
df.groupby('department').mean(numeric_only=True)
df.groupby(['Salary','Experience']).sum()

  department Employee  Salary  Experience
0         IT        A   50000           2
1         IT        B   60000           4
2         HR        C   65000           3
3    finance        D   45000           1
4         HR        E   70000           4
5         IT        F   70000           5

                  department Employee
Salary Experience
45000  1             finance        D
50000  2                  IT        A
60000  4                  IT        B
65000  3                  HR        C
70000  4                  HR        E
       5                  IT        F

In [21]:
df.groupby('department',as_index=True).sum()

            Salary  Experience
department
HR          135000           7
IT          180000          11
finance      45000           1

In [22]:
df.groupby('department',sort=True).sum()

            Salary  Experience
department
HR          135000           7
IT          180000          11
finance      45000           1

In [16]:
df.groupby('department')['Salary'].sum()

department
HR          65000
Hr          70000
IT         180000
finance     45000
Name: Salary, dtype: int64

In [17]:
df.groupby('department').agg({'Salary':['mean','max'], 'Experience':['sum','mean']})

           Salary        Experience
             mean    max        sum      mean
department
HR          65000  65000          3  3.000000
Hr          70000  70000          4  4.000000
IT          60000  70000         11  3.666667
finance     45000  45000          1  1.000000

In [23]:
df.groupby('department')['Salary'].apply(lambda x:x.max()-x.min())

department
HR          5000
IT         20000
finance        0
Name: Salary, dtype: int64

In [25]:
grouped=df.groupby('department')
grouped.get_group('HR')

           Employee  Salary  Experience
department
HR                C   65000           3
IT                A   50000           2
finance           D   45000           1

In [26]:
df.groupby('department').nth(0)

           Employee  Salary  Experience
department
HR                C   65000           3
IT                A   50000           2
finance           D   45000           1

In [27]:
df.groupby('department').nth(1)

           Employee  Salary  Experience
department
HR                E   70000           4
IT                B   60000           4

In [28]:
df.groupby('department').nth(-1)

           Employee  Salary  Experience
department
HR                E   70000           4
IT                F   70000           5
finance           D   45000           1

In [29]:
df.groupby('department').groups

{'HR': [2, 4], 'IT': [0, 1, 5], 'finance': [3]}

In [43]:
df=pd.read_csv('imdb-top-1000.csv')

In [44]:
genres=df.groupby('Genre')

In [35]:
genres.sum()

           Runtime  IMDB_Rating  No_of_Votes         Gross  Metascore
Genre
Action       22196       1367.3     72282412  3.263226e+10    10499.0
Adventure     9656        571.5     22576163  9.496922e+09     5020.0
Animation     8166        650.3     21978630  1.463147e+10     6082.0
Biography    11970        698.6     24006844  8.276358e+09     6023.0
Comedy       17380       1224.7     27620327  1.566387e+10     9840.0
Crime        13524        857.8     33533615  8.452632e+09     6706.0
Drama        36049       2299.7     61367304  3.540997e+10    19208.0
Family         215         15.6       551221  4.391106e+08      158.0
Fantasy        170         16.0       146222  7.827267e+08        0.0
Film-Noir      312         23.9       367215  1.259105e+08      287.0
Horror        1123         87.0      3742556  1.034649e+09      880.0
Mystery       1429         95.7      4203004  1.256417e+09      633.0
Thriller       108          7.8        27733  1.755074e+07       81.0
Western        593         33.4      1289665  5.822151e+07      313.0

In [36]:
genres.describe()

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

In [37]:
df.groupby('Genre')['Gross'].sum()

Genre
Action       3.263226e+10
Adventure    9.496922e+09
Animation    1.463147e+10
Biography    8.276358e+09
Comedy       1.566387e+10
Crime        8.452632e+09
Drama        3.540997e+10
Family       4.391106e+08
Fantasy      7.827267e+08
Film-Noir    1.259105e+08
Horror       1.034649e+09
Mystery      1.256417e+09
Thriller     1.755074e+07
Western      5.822151e+07
Name: Gross, dtype: float64

In [38]:
df['Genre'].unique()

array(['Drama', 'Crime', 'Action', 'Biography', 'Western', 'Comedy',
       'Adventure', 'Animation', 'Horror', 'Mystery', 'Film-Noir',
       'Fantasy', 'Family', 'Thriller'], dtype=object)

In [39]:
df.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [45]:
genres=df.groupby('Genre')
df.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [46]:
genres=df.groupby('Genre')
df.groupby('Genre')['IMDB_Rating'].max().sort_values(ascending=False).head(1)

Genre
Drama    9.3
Name: IMDB_Rating, dtype: float64

In [47]:
genres=df.groupby('Genre')
df.groupby('Genre')['IMDB_Rating'].min().sort_values(ascending=False).head(1)

Genre
Fantasy    7.9
Name: IMDB_Rating, dtype: float64

In [51]:
df.groupby('Star1')['Series_Title'].count()

Star1
Aamir Khan              7
Aaron Taylor-Johnson    1
Abhay Deol              1
Abraham Attah           1
Adam Driver             1
                       ..
Zbigniew Zamachowski    1
Zooey Deschanel         1
Çetin Tekindor          1
Éric Toledano           1
Ömer Faruk Sorak        1
Name: Series_Title, Length: 660, dtype: int64

In [52]:
df.groupby('Genre').nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

In [53]:
df.groupby('Genre').count()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,172,172,172,172,172,172,172,143
Adventure,72,72,72,72,72,72,72,72,64
Animation,82,82,82,82,82,82,82,82,75
Biography,88,88,88,88,88,88,88,88,79
Comedy,155,155,155,155,155,155,155,155,125
Crime,107,107,107,107,107,107,107,107,87
Drama,289,289,289,289,289,289,289,289,241
Family,2,2,2,2,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,11,11,11,11,11,11,11
Mystery,12,12,12,12,12,12,12,12,8
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,4,4,4,4,4

In [54]:
df.groupby('Genre').size()

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [55]:
df.groupby('Genre').nth(0)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [56]:
df.groupby('Genre').nth(1)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Lord of the Rings: The Return of the King,2003,201,8.9,Peter Jackson,Elijah Wood,1642758,377845905.0,94.0
Adventure,Back to the Future,1985,116,8.5,Robert Zemeckis,Michael J. Fox,1058081,210609762.0,87.0
Animation,The Lion King,1994,88,8.5,Roger Allers,Rob Minkoff,942045,422783777.0,88.0
Biography,Goodfellas,1990,146,8.7,Martin Scorsese,Robert De Niro,1020727,46836394.0,90.0
Comedy,La vita è bella,1997,116,8.6,Roberto Benigni,Roberto Benigni,623629,57598247.0,59.0
Crime,The Godfather: Part II,1974,202,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
Drama,Fight Club,1999,139,8.8,David Fincher,Brad Pitt,1854740,37030102.0,66.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,The Maltese Falcon,1941,100,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
Horror,Alien,1979,117,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
Mystery,Rear Window,1954,112,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
Western,Once Upon a Time in the West,1968,165,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0